### ISSUE TITLE
Please fix Rails 3 incompatibility with dependencies!

### ISSUE THREAD

**Issue by rodrigoalvesvieira** [codebrew/mongoid_session_store#1]
Hello, today Rails 3 final was released and there is now an incompatibility problem between dependencies of mongoid_session_store and rails 3.0.0 on activesupport. There is the full report:

~/code/application[master] λ bundle install
Fetching source index for http://rubygems.org/
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    mongoid_session_store depends on
      activemodel (= 3.0.0.rc)

```
rails (= 3.0.0) depends on
  activemodel (3.0.0)
```

Please update the mongoid_session_store  dependencies!

Thanks!

**Comment by ryanfitz** [comment]
I just released version 1.0.0.beta1 which supports rails 3.0.0 you need to use the latest mongoid git version to support 3.0.0 also. In your gemfile gem "mongoid", :git => "http://github.com/mongoid/mongoid.git"

Let me know if you run into any issues.

**Comment by rodrigoalvesvieira** [comment]
Thanks Ryan, great support! Everything is working now with Rails 3 final! Thanks!

**Comment by ryanfitz** [comment]
Good to hear that its working, I just released version 1.0.0

It includes a rake task to clear out sessions held in mongo and also automatically configures your app to use it for storing sessions. The readme is updated to reflect those changes, let me know if you have any questions and/or if the readme should be changed.

**Comment by rodrigoalvesvieira** [comment]
Thank you again!  Ryan! Everything is working as expected! Nice to see mongoid_session_store hitting 1.0.0!
